import type { NextPage } from "next";
import Head from "next/head";
import css from "./index.module.scss";
import ProductCard from "../components/product-card";
import { commerce } from "../lib/commerce";
import { Product } from "@chec/commerce.js/types/product";
import { Merchant } from "@chec/commerce.js/types/merchant";
import { ArrowRight, Menu } from "react-feather";
import Image from 'next/image'
import Link from "next/link";
import Header from "../components/header";
import Img from "@/components/image/image";

interface IHome {
	products: Product[];
	merchant: Merchant;
}

export async function getStaticProps() {
	const merchant = await commerce.merchants.about();
	const { data: products } = await commerce.products.list();

	return {
		props: {
			merchant,
			products,
		},
	};
}

const Home: NextPage<IHome> = ({ merchant, products }) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<Header />

			<main className={css.main}>

				<section className={`${css.section} ${css.intro}`}>

					<div className={`${css.left} ${css.heading_container}`}>
						<div className={css.section_title}>Artist designer based in London, UK</div>
						<div className={css.section_statement}>
							<p>Simon Renault</p>
						</div>
						<div className={css.button_link}>
							Explore all
							<ArrowRight size={24} className={css.icon} />
						</div>
					</div>

					<div className={css.right}>
						<Img src="/images/elephant.jpg" className={css.intro_image} />
					</div>

				</section>


				<section className={css.section}>
					<div className={css.heading_container}>
						<div className={css.section_title}>Collection</div>
						<div className={css.section_statement}>
							<p>Latest Creations</p>
						</div>
						<div className={css.button_link}>
							Explore all
							<ArrowRight size={24} className={css.icon} />
						</div>
					</div>
					<div className={css.grid}>
						{products.map((p) => {
							return <ProductCard product={p} key={p.name} />;
						})}
					</div>
				</section>


				<section className={css.section}>
					<div className={`${css.center} ${css.heading_container}`}>
						<div className={css.section_title}>About Us</div>
						<div className={css.section_statement}>
							<p>Write a big, bold statement about your brand.</p>
						</div>
						<div className={css.button_link}>
							Learn More
							<ArrowRight size={24} className={css.icon} />
						</div>
					</div>
				</section>

				<section className={css.section}>
					<Image src="/images/elephant.jpg" layout="intrinsic" width={5075} height={3580} />
				</section>


			</main>

			<footer className={css.footer}></footer>
		</div>
	);
};

export default Home;
