import type { NextPage } from "next";
import Head from "next/head";
import css from "./index.module.scss";
import ProductCard from "../components/product-card";
import { commerce } from "../lib/commerce";
import { Product } from "@chec/commerce.js/types/product";
import { Merchant } from "@chec/commerce.js/types/merchant";
import { ArrowRight } from "react-feather";
import Image from 'next/image'
import Img from "@/components/image/image";
import { motion } from "framer-motion";
import Grid from "@/components/sections/grid";
import classNames from "classnames";

interface IHome {
	products: Product[];
	merchant: Merchant;
}

export async function getStaticProps() {
	const merchant = await commerce.merchants.about();
	const { data: products } = await commerce.products.list();

	return {
		props: {
			merchant,
			products,
		},
	};
}

const transition = { duration: 1.4, ease: [0.6, 0.01, -0.05, 0.9] };

const firstName = {
	initial: {
		y: 0,
	},
	animate: {
		y: 0,
		transition: {
			delayChildren: 0.6,
			staggerChildren: 0.04,
			staggerDirection: -1,
		},
	},
};

const lastName = {
	initial: {
		y: 0,
	},
	animate: {
		y: 0,
		transition: {
			delayChildren: 0.6,
			staggerChildren: 0.04,
			staggerDirection: 1,
		},
	},
};

const letter = {
	initial: {
		y: 400,
	},
	animate: {
		y: 0,
		transition: { ...transition },
	},
};

const Home: NextPage<IHome> = ({ products }) => {
	return (
		<motion.div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
			</Head>

			<motion.main className={css.main} initial='initial'
				animate='animate'
				exit='exit'>

				<motion.section className={`${css.section} ${css.intro}`} >
					<div className={`${css.left} ${css.heading_container}`}>
						<div className={css.section_title}>Artist designer based in London, UK</div>
						<div className={css.section_statement}>
							<motion.p className={css.first} variants={firstName}>
								<motion.span variants={letter}>S</motion.span>
								<motion.span variants={letter}>i</motion.span>
								<motion.span variants={letter}>m</motion.span>
								<motion.span variants={letter}>o</motion.span>
								<motion.span variants={letter}>n</motion.span>
							</motion.p>
							{" "}
							<motion.p className={css.last} variants={lastName}>
								<motion.span variants={letter}>R</motion.span>
								<motion.span variants={letter}>e</motion.span>
								<motion.span variants={letter}>n</motion.span>
								<motion.span variants={letter}>a</motion.span>
								<motion.span variants={letter}>u</motion.span>
								<motion.span variants={letter}>l</motion.span>
								<motion.span variants={letter}>t</motion.span>
							</motion.p>
						</div>

						<div className={css.button_link}>
							Explore all
							<ArrowRight size={24} className={css.icon} />
						</div>

					</div>

					<motion.div className={css.right} initial={{ opacity: 0, y: 20 }}
						animate={{
							opacity: 1,
							y: 0,
							transition: { delay: 1.2, ...transition },
						}}>
						<Img src="/images/elephant.jpg" className={css.intro_image} />
					</motion.div>



				</motion.section>


				<section className={classNames(css.section)}>
					<div className={css.heading_container}>
						<div className={css.section_title}>Collection</div>
						<div className={css.section_statement}>
							<p>Latest Creations</p>
						</div>
						<div className={css.button_link}>
							Explore all
							<ArrowRight size={24} className={css.icon} />
						</div>
					</div>

				</section>

				<Grid items={
					[...products.map((p) => {
						return <ProductCard product={p} key={p.name} />;
					}), <Image src="/images/elephant.jpg" alt="test" key="test" layout="intrinsic" width={200} height={300} />]
				} />

				<section className={css.section}>
					<div className={`${css.center} ${css.heading_container}`}>
						<div className={css.section_title}>About Us</div>
						<div className={css.section_statement}>
							<p>Write a big, bold statement about your brand.</p>
						</div>
						<div className={css.button_link}>
							Learn More
							<ArrowRight size={24} className={css.icon} />
						</div>
					</div>
				</section>

				<section className={css.section}>
					<Image src="/images/elephant.jpg" layout="intrinsic" width={5075} height={3580} />
				</section>

			</motion.main>

			<footer className={css.footer}></footer>
		</motion.div>
	);
};

export default Home;
